signed commit...

diff --git a/bin/git-commit b/bin/git-commit
--- a/bin/git-commit
+++ b/bin/git-commit
@@ -3,7 +3,21 @@ source "common.sh"
 
 # Record changes to the repository
 
-git commit --all --gpg-sign="${ID_GPG_KEY}" --message "${1:-signed commit message...}"
+message="$1"
+
+if [ ! "$message" ]; then
+  log_warn "Message empty!"
+  # message="$(basename $PWD)-$(date "+%Y.%m.%d-%H:%M:%S"): signed commit..."
+  message="signed commit..."
+fi
+
+git commit --all --gpg-sign="${ID_GPG_KEY}" --message "$message"
+
+#if ! git commit --all --gpg-sign="${ID_GPG_KEY}" --message $message >/dev/null 2>/dev/null; then
+#  log_warn "An error occurred when record changes"
+#fi
+
+log_success $message
 
 read -r -p "Push to the repository? [y/N]" git_push
 
diff --git a/bin/git-push b/bin/git-push
--- a/bin/git-push
+++ b/bin/git-push
@@ -6,6 +6,16 @@ source "common.sh"
 
 remote="${1:---all}"
 
-log_info "git push origin: $remote"
+if [ ! "$remote" ]; then
+  log_error "Remote name empty!"
+fi
 
-git push origin $remote --follow-tags --verify
+question="git push$COLOR_PURPLE origin: $COLOR_RED$remote$COLOR_RESET? [y/N]"
+
+read -r -p "$(echo $question)" git_push
+
+if [[ "$git_push" =~ ^([yY][eE][sS]|[yY])$ ]]; then
+  if ! git push origin $remote --follow-tags --verify >/dev/null 2>/dev/null; then
+    log_warn "An error occurred when pushing: $remote"
+  fi
+fi
