signed commit...

diff --git a/bin/git-commit b/bin/git-commit
--- a/bin/git-commit
+++ b/bin/git-commit
@@ -11,13 +11,11 @@ if [ ! "$message" ]; then
   message="signed commit..."
 fi
 
-git commit --all --gpg-sign="${ID_GPG_KEY}" --message "$message"
+if ! git commit --all --gpg-sign="${ID_GPG_KEY}" --message "$message" >/dev/null 2>/dev/null; then
+  log_warn "An error occurred when record changes"
+fi
 
-#if ! git commit --all --gpg-sign="${ID_GPG_KEY}" --message $message >/dev/null 2>/dev/null; then
-#  log_warn "An error occurred when record changes"
-#fi
-
-log_success $message
+log_success "$message"
 
 read -r -p "Push to the repository? [y/N]" git_push
 
