commit...

diff --git a/bin/shell-common b/bin/shell-common
--- a/bin/shell-common
+++ b/bin/shell-common
@@ -1,75 +1,7 @@
 #!/bin/zsh
 
 # Be very strict
-#set -euo pipefail
 set -e
-
-#######################################################################
-# Default configuration
-#######################################################################
-
-#readonly date_time=$(date +"%Y/%m/%d %H:%M:%S")
-#readonly utc_date_time=$(date -u +"%Y/%m/%dT%H:%M:%SZ")
-
-# Shell working directory
-#readonly SHELL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-#export $SHELL_DIR
-
-# Current working directory
-readonly SHELL_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
-
-if [ ! -d $SHELL_DIR ]; then
-  printf "\033[0;31m[error]\033[0m: %s\\n" "Error: The current working directory doesn't exist, cannot proceed."
-  exit 1
-fi
-
-# shellcheck source=./shell-colors
-#source "${SHELL_DIR}/shell-colors"
-
-# shellcheck source=./shell-logger
-#source "${SHELL_DIR}/shell-logger"
-
-#######################################################################
-# logger
-#######################################################################
-
-## https://apple.stackexchange.com/questions/256769/how-to-use-logger-command-on-sierra
-
-log_info()
-{
-  printf "\033[0;34m[info]\033[0m: %s\\n" "$1"
-  # logger -p user.info -t "$(basename $0)" "$@"
-}
-
-log_success()
-{
-  printf "\033[0;32m[success]\033[0m: %s\\n" "$1"
-  # logger -p user.notice -t "$(basename $0)" "$@"
-}
-
-log_warn()
-{
-  printf "\033[0;33m[warn]\033[0m: %s\\n" "$1"
-  # logger -p user.warn -t "$(basename $0)" "$@"
-}
-
-log_alert()
-{
-  printf "\033[0;33m[alert]\033[0m: %s\\n" "$1"
-  # logger -p user.alert -t "$(basename $0)" "$@"
-}
-
-log_error()
-{
-  printf "\033[0;31m[error]\033[0m: %s\\n" "$1"
-  # logger -p user.error -t "$(basename $0)" "$@"
-}
-
-error_exit()
-{
-  log_error "$1" >&2
-  exit 1
-}
 
 #######################################################################
 # Load environment variables
@@ -81,35 +13,40 @@ for file in ${HOME}/.{env,env.local}; do
 done
 unset file
 
-if [ -z $SHELL_PROFILE_DEBUG ]; then
-  error_exit "An error occurred, the value of the variable SHELL_PROFILE_DEBUG was not loaded!"
+#######################################################################
+# Load source files
+#######################################################################
+
+#if [ ! -d "$SHELL_BIN" ]; then
+#  printf "\033[0;31m[error]\033[0m: %s\\n" "Error: The current working directory doesn't exist, cannot proceed."
+#  exit 1
+#fi
+
+# shellcheck source=./shell-colors
+source "${SHELL_BIN}/shell-colors"
+
+# shellcheck source=./shell-logger
+source "${SHELL_BIN}/shell-logger"
+
+#######################################################################
+# Check environment variables
+#######################################################################
+
+if [ -z $SHELL_DEBUG ]; then
+  error_exit "An error occurred, the value of the variable SHELL_DEBUG was not loaded!"
 fi
 
-if [ -z $SHELL_PROFILE_BIN ]; then
-  error_exit "An error occurred, the value of the variable SHELL_PROFILE_BIN was not loaded!"
+if [ -z $SHELL_BIN ]; then
+  error_exit "An error occurred, the value of the variable SHELL_BIN was not loaded!"
 fi
 
 #######################################################################
-# Initialization
+# Check system required dependencies
 #######################################################################
 
-#...
+declare -a commands=()
 
-#######################################################################
-# Load all tools
-#######################################################################
-
-#for file in $SHELL_PROFILE_BIN/*/*; do
-#  [ -r "$file" ] && [ -f "$file" ] && echo "$file"
-#done
-#unset file
-
-
-###
-### System dependencies
-### log_info 'Check system required dependencies'
-
-declare -a commands=(
+commands=(
   docker
   docker-compose
   git
@@ -123,8 +60,21 @@ declare -a commands=(
   hadolint
 )
 
-for command in "${commands[@]}"; do
-  if ! command -v "$command" >/dev/null 2>/dev/null; then
-    log_warn "${command} is not installed."
-  fi
-done
+#for command in "${commands[@]}"; do
+#  if ! command -v "$command" >/dev/null 2>/dev/null; then
+#    log_warn "${command} is not installed."
+#  fi
+#done
+
+#######################################################################
+# Private functions
+#######################################################################
+
+#readonly date_time=$(date +"%Y/%m/%d %H:%M:%S")
+#readonly utc_date_time=$(date -u +"%Y/%m/%dT%H:%M:%SZ")
+
+#######################################################################
+# Initialization
+#######################################################################
+
+#...
