commit...

diff --git a/bin/git/git-commit b/bin/git/git-commit
--- a/bin/git/git-commit
+++ b/bin/git/git-commit
@@ -4,7 +4,7 @@
 source "${SHELL_BIN}/shell-common"
 
 # Record changes to the repository
-readonly message="$1"
+message="${1:-commit...}"
 
 if [ ! "$message" ]; then
   log_error "Commit message empty!"
@@ -16,13 +16,10 @@ else
   log_success "Commit id: $(git rev-parse --short HEAD)"
 fi
 
-# git-push
-# git-push $(git-branch-name)
+read -r -p "Push to the repository? [y/N]" git_push
 
-#read -r -p "Push to the repository? [y/N]" git_push
-#
-#if [[ "$git_push" =~ ^([yY][eE][sS]|[yY])$ ]]; then
-#  if ! git push origin --follow-tags >/dev/null 2>/dev/null; then
-#    log_warn "An error occurred when pushing tag: $tag_name"
-#  fi
-#fi
+if [[ "$git_push" =~ ^([yY][eE][sS]|[yY])$ ]]; then
+  if ! git push origin --follow-tags >/dev/null 2>/dev/null; then
+    log_warn "An error occurred when pushing tag: $tag_name"
+  fi
+fi
