Signing commit 27-08-2021

diff --git a/bin/git/git-commit b/bin/git/git-commit
--- a/bin/git/git-commit
+++ b/bin/git/git-commit
@@ -24,22 +24,28 @@ commit_message="Signing commit $(date +%d-%m-%Y)"
 commit_push=false
 commit_branch=$(git rev-parse --abbrev-ref HEAD) >/dev/null 2>/dev/null
 
+declare -i interactive=1
+
 # Getops does not support long option names
 while [[ $# -gt 0 ]]; do
   case $1 in
-    -m=* | --message=*)
-      commit_message="${1#*=}"
-      shift # past value
-      ;;
-    -p | --push)
-      commit_push=true
-      shift # past value
-      ;;
-    *)
-      output "Unknown option $1" "error"
-      output "Usage: ${0} [-m|--message=\"commit...\" --push]" "error"
-      exit 1
-      ;;
+  -m=* | --message=*)
+    commit_message="${1#*=}"
+    shift # past value
+    ;;
+  -p | --push)
+    commit_push=true
+    shift # past value
+    ;;
+  --no-interactive)
+    interactive=0
+    shift # past value
+    ;;
+  *)
+    output "Unknown option $1" "error"
+    output "Usage: ${0} [-m|--message=\"commit...\" --push]" "error"
+    exit 1
+    ;;
   esac
 done
 
@@ -55,6 +61,16 @@ output "$(printf "Email:\t $COLOR_BLUE%s$COLOR_RESET" "$GIT_EMAIL")" "info"
 output "$(printf "GPG key: $COLOR_YELLOW%s$COLOR_RESET" "$GIT_GPG_KEY")" "info"
 output "$(printf "Branch:\t $COLOR_CYAN%s$COLOR_RESET 📝" "$commit_branch")" "info"
 output "$(printf "Commit:\t $COLOR_CYAN%s$COLOR_RESET 📝" "$commit_message")" "info"
+
+output $commit_push
+
+if [ "$interactive" -eq 0 ]; then
+  if ! git commit -S --all --message "$commit_message" >/dev/null 2>/dev/null; then
+    output "An error occurred when record changes" 'error'
+  fi
+fi
+
+exit 0
 
 read_boolean "Commit changes?" true || {
   if ! git commit -S --all --message "$commit_message" >/dev/null 2>/dev/null; then
